### ISSUE TITLE
Getting empty response from both core and 1core

### ISSUE THREAD

**Issue by ChelonianEgghead** [wibyweb/wiby#7]
I'm not sure what's going on but both core and 1core keep sending empty responses and giving this error message whenever I try doing anything with Wiby. Any idea what's up and how I can troubleshoot it?

```2023/04/06 20:29:50 http: panic serving 127.0.0.1:34116: runtime error: invalid memory address or nil pointer dereference
goroutine 7 [running]:
net/http.(*conn).serve.func1(0xc0000790e0)
        /usr/lib/go-1.15/src/net/http/server.go:1801 +0x147
panic(0x798680, 0xa63cb0)
        /usr/lib/go-1.15/src/runtime/panic.go:975 +0x47a
html/template.(*Template).escape(0x0, 0x0, 0x0)
        /usr/lib/go-1.15/src/html/template/template.go:95 +0x3b
html/template.(*Template).Execute(0x0, 0x869060, 0xc0000ac0e0, 0x798380, 0xaa4470, 0x8691c0, 0xc000063740)
        /usr/lib/go-1.15/src/html/template/template.go:119 +0x2f
main.handler(0x86ea40, 0xc0000ac0e0, 0xc0000f2000)
        /home/stephenvk/wiby/go/core/1core.go:106 +0x5fc5
net/http.HandlerFunc.ServeHTTP(0x813d00, 0x86ea40, 0xc0000ac0e0, 0xc0000f2000)
        /usr/lib/go-1.15/src/net/http/server.go:2042 +0x44
net/http.(*ServeMux).ServeHTTP(0xa74260, 0x86ea40, 0xc0000ac0e0, 0xc0000f2000)
        /usr/lib/go-1.15/src/net/http/server.go:2417 +0x1ad
net/http.serverHandler.ServeHTTP(0xc0000ac000, 0x86ea40, 0xc0000ac0e0, 0xc0000f2000)
        /usr/lib/go-1.15/src/net/http/server.go:2843 +0xa3
net/http.(*conn).serve(0xc0000790e0, 0x86f540, 0xc00004a440)
        /usr/lib/go-1.15/src/net/http/server.go:1925 +0x8ad
created by net/http.(*Server).Serve
        /usr/lib/go-1.15/src/net/http/server.go:2969 +0x36c```

**Comment by wibyweb** [comment]
Hi, do you have the coreassets folder saved in the same location as 1core? It is failing to read the template files.

**Comment by wibyweb** [comment]
Didn't hear back

**Comment by ChelonianEgghead** [comment]
Hello, sorry for the late reply, life's been kind of taking me on a roller coaster ride as of late. Yes, they're both saved in the same directory, turns out it was just a permissions issue. Thanks for your time!

**Comment by wibyweb** [comment]
No problem!
